[functions]
  directory = "netlify/functions"
  # DIES WAR DER FEHLER: Das Timeout darf nicht direkt unter [functions] stehen.

# WICHTIG: Definiert den Build-Schritt, um die Python-Funktion ausführbar zu machen.
[build]
  command = "chmod +x netlify/functions/generate.py"
  
# Wir definieren das Timeout wieder spezifisch für unsere 'generate' Funktion.
[functions.generate]
  timeout = 26

