[functions]
directory = "netlify/functions"

[build]
  # Erst Pakete installieren, DANN chmod ausf√ºhren
command = "pip install -r requirements.txt && chmod +x netlify/functions/generate.py"

[functions.generate]
timeout = 26
